### ISSUE TITLE
When making a sale, save new payment methods for later use

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-service#140]
When you submit a new payment token to the subscription API, it automatically saves it for later use. We should do the same thing with the sale API (as long as the user is signed in). I actually added this as part of https://github.com/mozilla/payments-service/pull/139 but I reverted it in https://github.com/mozilla/payments-service/commit/f9b2ec5971cdd9535ed5b2428c010969a0a76179 because of the following traceback. We might need to do this on the solitude side instead, maybe when we create the initial sale or something.

```
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/payments-service/payments_service/braintree/views/sale.py", line 40, in post
    'nonce': form.cleaned_data['nonce'],
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/curling/lib.py", line 186, in post
    headers=headers, params=kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/curling/lib.py", line 299, in _request
    response=resp, content=self._try_to_serialize_error(resp))
HttpClientError: Client Error 422: http://solitude:2602/braintree/paymethod/
Content: {u'braintree': {u'payment_method_nonce': [{u'message': u'Cannot use a payment_method_nonce more than once.', u'code': u'93107'}]}}
```

Supports: https://github.com/mozilla/payments/issues/117

**Comment by kumar303** [comment]
This is starting to feel a little bit gnarly so I'm going to set it aside for a bit. Even if we implement this, it won't have any meaning until we provide a way in the UI to sign in before making a donation.

Here are some experimental patches that seem to mostly work:

payments-service:

``` diff
diff --git a/payments_service/auth/__init__.py b/payments_service/auth/__init__.py
index c0ab2bb..d88b861 100644
--- a/payments_service/auth/__init__.py
+++ b/payments_service/auth/__init__.py
@@ -21,6 +21,7 @@ class SolitudeBuyer(AnonymousUser):
     is_active = True

     def __init__(self, buyer_uuid, buyer_pk):
+        # TODO: add braintree buyer pk and uri
         self.pk = self.id = buyer_pk
         self.uuid = buyer_uuid
         self.uri = '/generic/buyer/{0}/'.format(self.pk)
diff --git a/payments_service/braintree/views/sale.py b/payments_service/braintree/views/sale.py
index 139a162..1fcc455 100644
--- a/payments_service/braintree/views/sale.py
+++ b/payments_service/braintree/views/sale.py
@@ -19,13 +19,18 @@ class Sale(AnonymousSolitudeAPIView):
         form = SaleForm(request.user, request.DATA)
         if not form.is_valid():
             return error_400(response=form.errors)
+
+        sale_data = {
+            'amount': form.cleaned_data['amount'],
+            'product_id': form.cleaned_data['product_id'],
+            'nonce': form.cleaned_data['nonce'],
+            #'braintree_buyer': '/braintree/mozilla/buyer/1/',
+            'paymethod': form.cleaned_data['paymethod'],
+        }
+        if request.user:
+            sale_data['braintree_buyer'] = request.user.braintree_buyer_uri
         try:
-            self.api.braintree.sale.post({
-                'amount': form.cleaned_data['amount'],
-                'product_id': form.cleaned_data['product_id'],
-                'nonce': form.cleaned_data['nonce'],
-                'paymethod': form.cleaned_data['paymethod'],
-            })
+            self.api.braintree.sale.post(sale_data)
             log.info('posted a sale for user/product: {}/{}'
                      .format(request.user, form.cleaned_data['product_id']))
         except HttpClientError, exc:

```

Solitude:

``` diff
diff --git a/lib/brains/forms.py b/lib/brains/forms.py
index fbc83f9..7e1ea8c 100644
--- a/lib/brains/forms.py
+++ b/lib/brains/forms.py
@@ -75,7 +75,7 @@ class PaymentMethodForm(forms.Form):
             'payment_method_nonce': self.cleaned_data['nonce'],
             # This will force the card to be verified upon creation.
             'options': {
-                'verify_card': True
+                'verify_card': True,
             }
         }

@@ -229,6 +229,11 @@ class SaleForm(forms.Form):
     amount = forms.DecimalField(
         max_value=Decimal(settings.BRAINTREE_MAX_AMOUNT),
         min_value=Decimal(settings.BRAINTREE_MIN_AMOUNT))
+    braintree_buyer = PathRelatedFormField(
+        view_name='braintree:mozilla:buyer-detail',
+        queryset=BraintreeBuyer.objects.filter(),
+        required=False,
+        allow_null=True)
     # This will be populated by the paymethod.
     buyer = None
     nonce = forms.CharField(max_length=255, required=False)
@@ -307,7 +312,9 @@ class SaleForm(forms.Form):
         data = {
             'amount': self.cleaned_data['amount'],
             'options': {
-                'submit_for_settlement': True
+                'submit_for_settlement': True,
+                # Only do this with a flag.
+                'store_in_vault_on_success': True,
             }
         }
         if self.cleaned_data.get('paymethod'):
diff --git a/lib/brains/views/sale.py b/lib/brains/views/sale.py
index 14db316..b2f6996 100644
--- a/lib/brains/views/sale.py
+++ b/lib/brains/views/sale.py
@@ -4,11 +4,12 @@ from rest_framework.response import Response
 from lib.brains.client import get_client
 from lib.brains.errors import BraintreeResultError
 from lib.brains.forms import SaleForm
-from lib.brains.models import BraintreeTransaction
+from lib.brains.models import BraintreePaymentMethod, BraintreeTransaction
 from lib.brains.serializers import LocalTransaction, Namespaced
 from lib.transactions import constants
 from lib.transactions.models import Transaction
 from lib.transactions.serializers import TransactionSerializer
+from solitude.constants import PAYMENT_METHOD_CARD
 from solitude.errors import FormError
 from solitude.logger import getLogger

@@ -52,6 +53,20 @@ def create(request):
     log.info('BraintreeTransaction created: {}'
              .format(braintree_transaction.pk))

+    if form.cleaned_data['nonce'] and form.cleaned_data['braintree_buyer']:
+        saved_paymethod = BraintreePaymentMethod.objects.create(
+            active=True,
+            type=PAYMENT_METHOD_CARD,
+            type_name=result.transaction.credit_card['card_type'],
+            braintree_buyer=form.cleaned_data['braintree_buyer'],
+            provider_id=result.transaction.credit_card['token'],
+            truncated_id=result.transaction.credit_card['last_4'],
+        )
+        log.info('stored payment method {} from one-time sale '
+                 'for braintree buyer {}'
+                 .format(saved_paymethod.pk,
+                         form.cleaned_data['braintree_buyer'].pk))
+
     res = Namespaced(
         braintree={},  # Not sure if there's anything useful to add here.
         mozilla={

```

**Comment by kumar303** [comment]
This pretty much just turned into a headache and I don't think it's very important. We don't have any way in the UI to sign in while making a donation anyway. This could be useful one day if donations get some use.
